### ISSUE TITLE
Use self-implemented SecretKey class

### ISSUE THREAD

**Issue by infeo** [cryptomator/cryptolib#19]
The `Masterkey` class, holding the encryption and authentification keys, implements the [SecretKey](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/javax/crypto/SecretKey.html) interface of the JDK. A requirement is to implement a `destroy()` method. But secret keys generated by JDK internals cannot be destroyed:
```
jshell> var key2 = KeyGenerator.getInstance("AES").generateKey()
key2 ==> javax.crypto.spec.SecretKeySpec@174bd
jshell> key2.getEncoded()
$7 ==> byte[16] { 11, -92, -5, -2, -11, 59, -17, -116, -115, -47, 34, 112, 53, 59, 60, 99 }
jshell> key2.destroy()
|  Exception javax.security.auth.DestroyFailedException
|        at Destroyable.destroy (Destroyable.java:54)
|        at (#8:1)
```

This holds true for all keys implemented by the JDK default class SecretKeyImpl. As this won't be fixed (see [JDK bug tracker](https://bugs.openjdk.java.net/browse/JDK-8160206?jql=text%20~%20%22SecretKey%20not%20destroy%22)), we should provide our own SecretKey implementation.

Requirements for the impl are:
* throw `IllegalStateException` on access attempt of an already destroyed key
* `equals()` has a runtime of O(1)
* `hashcode()` and `equals()` must be based onto the key material
* `destroy()` is idempotent
* override  `ObjectOutputStream.writeObject(java.lang.Object)` to prevent keys that have been destroyed from being serialized
* tbd

There exists already an implementation in the [`Scrypt`](https://github.com/cryptomator/cryptolib/blob/1186fca3fa2b1ae9594dfe72b4e66ea95f680904/src/main/java/org/cryptomator/cryptolib/common/Scrypt.java#L99) class, which fullfills some of the requirements.

**Comment by overheadhunter** [comment]
fixed in 2.0.0-beta6
