### ISSUE TITLE
Documentation: How many rounds of AES-256 are used?

### ISSUE THREAD

**Issue by a20eac1d** [cryptomator/cryptolib#30]
Over the years there have been numerous attacks on AES-256 with 9, 10 and 11 rounds.

( https://www.schneier.com/blog/archives/2009/07/another_new_aes.html )

Unfortunately, I was unable to find any information stating how many rounds of AES-256 encryption are being used by Cryptomator / cryptolib? Is this library vulnerable against any known attacks that could compromise its security?

I think it would be a good idea to add this to the documentation.

**Comment by overheadhunter** [comment]
14 rounds, as per spec. The number of rounds can not be freely chosen (if adhering to agreed-upon standards). The blog post is about updating the standard and increase the number of rounds.
