### ISSUE TITLE
compile error on android

### ISSUE THREAD

**Issue by jjhesk** [cryptomator/cryptolib#6]
i got this.. on buildtool 3.0.0
Error:com.android.builder.dexing.DexArchiveBuilderException: Error while dexing org/cryptomator/cryptofs/CryptoPathFactory.class

**Comment by tobihagemann** [comment]
@markuskreusch Any ideas?

**Comment by overheadhunter** [comment]
Wrong repo. Class name suggests that you're using [CryptoFS](https://github.com/cryptomator/cryptofs), not CryptoLib. CryptoFS is not Android compatible.
