### ISSUE TITLE
Scrypt takes a long time to finish on android.

### ISSUE THREAD

**Issue by mehranagh20** [cryptomator/cryptolib#9]
I tried to use scrypt function of Cryptolib in android with its 32768 default parameter as 'n', but it takes a long time to finish.
Is that normal or i am doing something wrong?
I think you've used it in android cryptomator so i can't understand the problem happening here.

**Comment by overheadhunter** [comment]
When you say "a long time", what duration are we talking about?

**Comment by markuskreusch** [comment]
@mehranagh20 I had similar issues when running Cryptomator in debug mode during development of the app. The things done on the Android device to allow debugging seem to slow down Scrypt pretty much. When building a release APK and testing with that, the problems were gone. Scrypt still may take some time (around 1 second in my tests) but that is required to protect the password.

**Comment by mehranagh20** [comment]
@overheadhunter that was around 1 minute.
@markuskreusch i tried that and that works just fine :)
That totally solved my problem.
Thanks.

I think this should get closed now.
